#!/bin/bash

if [ -z "${1}" ]; then
  echo "Getting the clusters you have access to..."
  NAMES=($(ibmcloud oc cluster ls -q | grep openshift | awk '{print $1}'))

  [ -z "$NAMES" ] && echo "No openshift clusters found" && exit 1

  echo
  echo "Choose the cluster you want to log in to:"
  i=0
  for name in ${NAMES[@]}; do
  	i=$((i+1))
	  echo "${i}. $name"
  done
  read p

  p=$((p-1))
  name="${NAMES[$p]}"
else
  name="${1}"
fi

echo "Logging into the $name cluster..."
ibmcloud oc cluster config -c $name --admin || exit 1
#oc login -u apikey -p $(jq -r '.apikey' $keyfile) --server="${cluster}" || exit 1

ctx=$(kubectl config current-context)
kubectl config delete-context "${name}"
kubectl config rename-context "${ctx}" "${name}"
echo "Done."
